# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: canrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='canrpc.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\004main'),
  serialized_pb=_b('\n\x0c\x63\x61nrpc.proto\"#\n\x03\x43\x41N\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\x0c\"+\n\x0bSendCANArgs\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\x0c\"\x19\n\x0bReadCANArgs\x12\n\n\x02id\x18\x01 \x01(\t2Q\n\rCANRPCService\x12\x1f\n\x07SendCAN\x12\x0c.SendCANArgs\x1a\x04.CAN\"\x00\x12\x1f\n\x07ReadCAN\x12\x0c.ReadCANArgs\x1a\x04.CAN\"\x00\x42\x06Z\x04mainb\x06proto3')
)




_CAN = _descriptor.Descriptor(
  name='CAN',
  full_name='CAN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CAN.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='CAN.contents', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=51,
)


_SENDCANARGS = _descriptor.Descriptor(
  name='SendCANArgs',
  full_name='SendCANArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SendCANArgs.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='SendCANArgs.contents', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=96,
)


_READCANARGS = _descriptor.Descriptor(
  name='ReadCANArgs',
  full_name='ReadCANArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReadCANArgs.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['CAN'] = _CAN
DESCRIPTOR.message_types_by_name['SendCANArgs'] = _SENDCANARGS
DESCRIPTOR.message_types_by_name['ReadCANArgs'] = _READCANARGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CAN = _reflection.GeneratedProtocolMessageType('CAN', (_message.Message,), dict(
  DESCRIPTOR = _CAN,
  __module__ = 'canrpc_pb2'
  # @@protoc_insertion_point(class_scope:CAN)
  ))
_sym_db.RegisterMessage(CAN)

SendCANArgs = _reflection.GeneratedProtocolMessageType('SendCANArgs', (_message.Message,), dict(
  DESCRIPTOR = _SENDCANARGS,
  __module__ = 'canrpc_pb2'
  # @@protoc_insertion_point(class_scope:SendCANArgs)
  ))
_sym_db.RegisterMessage(SendCANArgs)

ReadCANArgs = _reflection.GeneratedProtocolMessageType('ReadCANArgs', (_message.Message,), dict(
  DESCRIPTOR = _READCANARGS,
  __module__ = 'canrpc_pb2'
  # @@protoc_insertion_point(class_scope:ReadCANArgs)
  ))
_sym_db.RegisterMessage(ReadCANArgs)


DESCRIPTOR._options = None

_CANRPCSERVICE = _descriptor.ServiceDescriptor(
  name='CANRPCService',
  full_name='CANRPCService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=125,
  serialized_end=206,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendCAN',
    full_name='CANRPCService.SendCAN',
    index=0,
    containing_service=None,
    input_type=_SENDCANARGS,
    output_type=_CAN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadCAN',
    full_name='CANRPCService.ReadCAN',
    index=1,
    containing_service=None,
    input_type=_READCANARGS,
    output_type=_CAN,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CANRPCSERVICE)

DESCRIPTOR.services_by_name['CANRPCService'] = _CANRPCSERVICE

# @@protoc_insertion_point(module_scope)
